services:
  # Atomic Services
  user-service:
    build: ./services/atomic/user-service
    container_name: mappalette-user-service
    ports:
      - "${USER_SERVICE_PORT:-3001}:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
    networks:
      - mappalette-network
    restart: unless-stopped

  post-service:
    build: ./services/atomic/post-service
    container_name: mappalette-post-service
    ports:
      - "${POST_SERVICE_PORT:-3002}:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
    networks:
      - mappalette-network
    restart: unless-stopped

  interaction-service:
    build: ./services/atomic/interaction-service
    container_name: mappalette-interaction-service
    ports:
      - "${INTERACTION_SERVICE_PORT:-3003}:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
    networks:
      - mappalette-network
    restart: unless-stopped

  follow-service:
    build: ./services/atomic/follow-service
    container_name: mappalette-follow-service
    ports:
      - "${FOLLOW_SERVICE_PORT:-3007}:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
    networks:
      - mappalette-network
    restart: unless-stopped

  # Composite Services
  feed-service:
    build: ./services/composite/feed-service
    container_name: mappalette-feed-service
    ports:
      - "${FEED_SERVICE_PORT:-3004}:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
      - USER_SERVICE_URL=http://user-service:5000
      - POST_SERVICE_URL=http://post-service:5000
      - INTERACTION_SERVICE_URL=http://interaction-service:5000
      - FOLLOW_SERVICE_URL=http://follow-service:5000
    depends_on:
      - user-service
      - post-service
      - interaction-service
      - follow-service
    networks:
      - mappalette-network
    restart: unless-stopped

  social-interaction-service:
    build: ./services/composite/social-interaction-service
    container_name: mappalette-social-interaction-service
    ports:
      - "${SOCIAL_INTERACTION_SERVICE_PORT:-3005}:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
      - USER_SERVICE_URL=http://user-service:5000
      - POST_SERVICE_URL=http://post-service:5000
      - INTERACTION_SERVICE_URL=http://interaction-service:5000
      - FOLLOW_SERVICE_URL=http://follow-service:5000
    depends_on:
      - user-service
      - post-service
      - interaction-service
      - follow-service
    networks:
      - mappalette-network
    restart: unless-stopped

  profile-service:
    build: ./services/composite/profile-service
    container_name: mappalette-profile-service
    ports:
      - "${PROFILE_SERVICE_PORT:-3006}:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
      - USER_SERVICE_URL=http://user-service:5000
      - POST_SERVICE_URL=http://post-service:5000
      - INTERACTION_SERVICE_URL=http://interaction-service:5000
      - FOLLOW_SERVICE_URL=http://follow-service:5000
    depends_on:
      - user-service
      - post-service
      - interaction-service
      - follow-service
    networks:
      - mappalette-network
    restart: unless-stopped

  explore-routes-service:
    build: ./services/composite/explore-routes-service
    container_name: mappalette-explore-routes-service
    ports:
      - "${EXPLORE_ROUTES_SERVICE_PORT:-3008}:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
      - USER_SERVICE_URL=http://user-service:5000
      - POST_SERVICE_URL=http://post-service:5000
    depends_on:
      - user-service
      - post-service
    networks:
      - mappalette-network
    restart: unless-stopped

  # golang (gin)
  leaderboard-service:
    build: ./services/composite/leaderboard-service
    container_name: mappalette-leaderboard-service
    ports:
      - "${LEADERBOARD_SERVICE_PORT:-8080}:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
      - USER_SERVICE_URL=http://user-service:5000
      - POST_SERVICE_URL=http://post-service:5000
    depends_on:
      - user-service
      - post-service
    networks:
      - mappalette-network
    restart: unless-stopped

  # java spring boot
  user-discovery-service:
    build: ./services/composite/user-discovery-service
    container_name: mappalette-user-discovery-service
    ports:
      - "${USER_DISCOVERY_SERVICE_PORT:-3010}:5000"
    env_file:
      - .env
    environment:
      - SERVER_PORT=5000
      - USER_SERVICE_URL=http://user-service:5000
      - FOLLOW_SERVICE_URL=http://follow-service:5000
    depends_on:
      - user-service
      - follow-service
    networks:
      - mappalette-network
    restart: unless-stopped

networks:
  mappalette-network:
    driver: bridge

volumes:
  node_modules: